In [1]:
import pandas as pd

In [2]:
dict_a = pd.DataFrame({'name' : ['anup', ' ram', 'hari'],
                      'roll no' : [7, 8 ,9],
                      'marks': [600,700,800]})
dict_b = pd.DataFrame({'name' : ['shyam', 'jhyam', 'lyam'],
                      'roll no' : [77, 88 ,99]})
pd.concat([dict_a,dict_b], axis = 0)

    name  roll no  marks
0   anup        7  600.0
1    ram        8  700.0
2   hari        9  800.0
0  shyam       77    NaN
1  jhyam       88    NaN
2   lyam       99    NaN

In [3]:
students = pd.DataFrame({
    'std_id':[2,3,4,5],
    'name': ['anup', 'kushal', 'aananta', 'dhiraj']
})

results = pd.DataFrame({
    'std_id':[1,2,3,4,5],
    'marks': [100,200,300,400,500],
    'gpa': [3.14,3.50,3.80,4.00,2.00]
})

pd.merge(students, results, on= 'std_id', how='right', indicator = True)

   std_id     name  marks   gpa      _merge
0       1      NaN    100  3.14  right_only
1       2     anup    200  3.50        both
2       3   kushal    300  3.80        both
3       4  aananta    400  4.00        both
4       5   dhiraj    500  2.00        both

In [4]:
left = pd.DataFrame({'id': [1, 2, 3], 'name': ['A', 'B', 'C']})
right = pd.DataFrame({'user_id': [1, 2, 4], 'score': [90, 85, 70]})
pd.merge(left, right, left_on='id', right_on='user_id', how='left')

   id name  user_id  score
0   1    A      1.0   90.0
1   2    B      2.0   85.0
2   3    C      NaN    NaN

- here the primary keys are different in both the tables and to tell the system
- which keys from left and which keys from the right to work on we use the left_on and right_on